Display flags and animations
sansaywm/firstproject pull request #3
Opened 2020-09-24 22:27 UTC by sansaywm

![Screenshot_2020-09-25-01-23-58-379_com example firstproject](https://user-images.githubusercontent.com/35571721/94206483-35f22080-fece-11ea-953b-0a0ab62081b6.jpg)
![Screenshot_2020-09-25-01-24-02-235_com example firstproject](https://user-images.githubusercontent.com/35571721/94206485-368ab700-fece-11ea-83a1-df6e675ecf4a.jpg)
![Screenshot_2020-09-25-01-24-06-658_com example firstproject](https://user-images.githubusercontent.com/35571721/94206487-37234d80-fece-11ea-8041-e570401b2d6d.jpg)

2020-09-25 07:37 UTC, stasenkots commented on app/src/main/java/com/example/firstproject/lesson2/Lesson2_animation.kt
> +        val buttonPrev = findViewById<Button>(R.id.buttonPrev)
We don't need to use findViewById

2020-09-25 07:40 UTC, stasenkots reviewed
Are your animation moving by itself or you must switch it?

2020-09-25 07:40 UTC, stasenkots commented on app/src/main/java/com/example/firstproject/lesson2/Lesson2_animation.kt
> +        val buttonNext = findViewById<Button>(R.id.buttonNext)
We don't need to use findViewById

2020-09-25 12:28 UTC, sansaywm commented
I must switch it

2020-09-25 12:30 UTC, sansaywm commented
I wanted to do it through a loop, but my phone crashed))

2020-09-25 17:28 UTC, Vladislav7776 approved these changes

2020-09-27 19:48 UTC, TMSlebedev requested changes

2020-09-27 19:48 UTC, TMSlebedev commented on app/src/main/java/com/example/firstproject/lesson2/Lesson2_animation.kt
> +        val buttonNext = findViewById<Button>(R.id.buttonNext)
Please use synthetic

2020-09-28 18:48 UTC, sansaywm commented on app/src/main/java/com/example/firstproject/lesson2/Lesson2_animation.kt
> +        val buttonNext = findViewById<Button>(R.id.buttonNext)
Thanks. Note has been corrected

2020-09-29 07:52 UTC, TMSlebedev approved these changes

2020-09-29 15:44 UTC, merged