Fitch monitor the harvest by region
sansaywm/firstproject pull request #4
Opened 2020-09-28 19:18 UTC by sansaywm

The victorious region is highlighted in green

![Screenshot_2020-09-28-22-04-57-252_com example firstproject](https://user-images.githubusercontent.com/35571721/94475774-3cd3a880-01d8-11eb-8a93-276293d2f47e.jpg)

2020-09-29 07:02 UTC, andrewKarachun0304 approved these changes

2020-09-29 07:55 UTC, stasenkots requested changes

2020-09-29 07:55 UTC, stasenkots commented on app/src/main/java/com/example/firstproject/lesson2/Lesson2_animation.kt
> +        val animator = findViewById<ViewAnimator>(R.id.view_Animation)
use syntetic

2020-09-29 07:55 UTC, stasenkots commented on app/src/main/java/com/example/firstproject/lesson3/myViewModel.kt
> +    var cabbageMogilev = MutableLiveData(0)
Better to create class to keep harvest data for each city

2020-09-29 13:09 UTC, limitAlltheir approved these changes

2020-09-29 14:28 UTC, TMSlebedev requested changes

2020-09-29 14:28 UTC, TMSlebedev commented on app/src/main/java/com/example/firstproject/lesson3/lesson3.kt
> +        myViewModel.potatoesMinsk.observe(this, Observer { newHarvestData ->
Try to group common logic. Too much code doubling

2020-10-01 10:20 UTC, Vladislav7776 approved these changes

2020-10-01 19:29 UTC, TMSlebedev approved these changes

2020-10-01 21:38 UTC, merged